function [C,dC] = BowlCC(in1,in2,in3)
%BOWLCC
%    [C,DC] = BOWLCC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    08-Feb-2020 16:30:36

M1_1 = in3(1);
M1_2 = in3(2);
M2_2 = in3(4);
dp1 = in1(4,:);
dp2 = in1(5,:);
dp3 = in1(6,:);
p1 = in1(1,:);
p2 = in1(2,:);
p3 = in1(3,:);
C = p3-p1.*(M1_1.*p1.*(1.0./2.0)+M1_2.*p2.*(1.0./2.0))-p2.*(M1_2.*p1.*(1.0./2.0)+M2_2.*p2.*(1.0./2.0));
if nargout > 1
    dC = dp3-dp1.*(M1_1.*p1+M1_2.*p2)-dp2.*(M1_2.*p1+M2_2.*p2);
end
