function gradC = BowlgraC(in1,in2)
%BOWLGRAC
%    GRADC = BOWLGRAC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    08-Feb-2020 16:30:36

M1_1 = in2(1);
M1_2 = in2(2);
M2_2 = in2(4);
p1 = in1(1,:);
p2 = in1(2,:);
gradC = [-M1_1.*p1-M1_2.*p2;-M1_2.*p1-M2_2.*p2;1.0];
