function [Mat,RHS] = BowlFile(t,in2,in3,in4)
%BOWLFILE
%    [MAT,RHS] = BOWLFILE(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    08-Feb-2020 16:30:36

M1_1 = in4(1);
M1_2 = in4(2);
M2_2 = in4(4);
dp1 = in2(4,:);
dp2 = in2(5,:);
g = in3(2,:);
m = in3(1,:);
p1 = in2(1,:);
p2 = in2(2,:);
t2 = -M1_1.*p1-M1_2.*p2;
t3 = -M1_2.*p1-M2_2.*p2;
Mat = reshape([m,0.0,0.0,t2,0.0,m,0.0,t3,0.0,0.0,m,1.0,t2,t3,1.0,0.0],[4,4]);
if nargout > 1
    RHS = [0.0;0.0;-g.*m;dp1.*(M1_1.*dp1+M1_2.*dp2)+dp2.*(M1_2.*dp1+M2_2.*dp2)];
end
